version: '3.9'
services:
    postgres:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
      volumes:
        - postgres-volume:/var/lib/postgresql/data
    
    keycloak:
      image: quay.io/keycloak/keycloak:15.0.2
      ports:
        - 8180:8080
      environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - DB_ADDR=postgres
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=keycloak
      depends_on:
        - postgres
volumes:
  postgres-volume: